package com.desksoft.entity;

import java.util.Date;

public class APoint {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column a_point.a_id
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	private String aId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column a_point.ma_id
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	private String maId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column a_point.user_id
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column a_point.user_name
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column a_point.lng
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	private String lng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column a_point.lat
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	private String lat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column a_point.gmt_create
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	private Date gmtCreate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column a_point.a_id
	 * @return  the value of a_point.a_id
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public String getaId() {
		return aId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column a_point.a_id
	 * @param aId  the value for a_point.a_id
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public void setaId(String aId) {
		this.aId = aId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column a_point.ma_id
	 * @return  the value of a_point.ma_id
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public String getMaId() {
		return maId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column a_point.ma_id
	 * @param maId  the value for a_point.ma_id
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public void setMaId(String maId) {
		this.maId = maId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column a_point.user_id
	 * @return  the value of a_point.user_id
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column a_point.user_id
	 * @param userId  the value for a_point.user_id
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column a_point.user_name
	 * @return  the value of a_point.user_name
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column a_point.user_name
	 * @param userName  the value for a_point.user_name
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column a_point.lng
	 * @return  the value of a_point.lng
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public String getLng() {
		return lng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column a_point.lng
	 * @param lng  the value for a_point.lng
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public void setLng(String lng) {
		this.lng = lng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column a_point.lat
	 * @return  the value of a_point.lat
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public String getLat() {
		return lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column a_point.lat
	 * @param lat  the value for a_point.lat
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public void setLat(String lat) {
		this.lat = lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column a_point.gmt_create
	 * @return  the value of a_point.gmt_create
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column a_point.gmt_create
	 * @param gmtCreate  the value for a_point.gmt_create
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}
}