package com.desksoft.entity;

import java.util.Date;

public class AReplay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_replay.r_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_replay.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_replay.ma_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String maId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_replay.user_name
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_replay.gmt_create
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_replay.content
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_replay.r_id
     *
     * @return the value of a_replay.r_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_replay.r_id
     *
     * @param rId the value for a_replay.r_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setrId(String rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_replay.user_id
     *
     * @return the value of a_replay.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_replay.user_id
     *
     * @param userId the value for a_replay.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_replay.ma_id
     *
     * @return the value of a_replay.ma_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getMaId() {
        return maId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_replay.ma_id
     *
     * @param maId the value for a_replay.ma_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setMaId(String maId) {
        this.maId = maId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_replay.user_name
     *
     * @return the value of a_replay.user_name
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_replay.user_name
     *
     * @param userName the value for a_replay.user_name
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_replay.gmt_create
     *
     * @return the value of a_replay.gmt_create
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_replay.gmt_create
     *
     * @param gmtCreate the value for a_replay.gmt_create
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_replay.content
     *
     * @return the value of a_replay.content
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_replay.content
     *
     * @param content the value for a_replay.content
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }
}