package com.desksoft.entity;

public class BindRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bind_relation.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bind_relation.b_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String bId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bind_relation.type
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bind_relation.open_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String openId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bind_relation.user_id
     *
     * @return the value of bind_relation.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bind_relation.user_id
     *
     * @param userId the value for bind_relation.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bind_relation.b_id
     *
     * @return the value of bind_relation.b_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getbId() {
        return bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bind_relation.b_id
     *
     * @param bId the value for bind_relation.b_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setbId(String bId) {
        this.bId = bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bind_relation.type
     *
     * @return the value of bind_relation.type
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bind_relation.type
     *
     * @param type the value for bind_relation.type
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bind_relation.open_id
     *
     * @return the value of bind_relation.open_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bind_relation.open_id
     *
     * @param openId the value for bind_relation.open_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }
}