package com.desksoft.entity;

import java.util.Date;

public class Language {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column language.languageId
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private String languageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column language.languageName
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private String languagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column language.creatDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private Date creatdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column language.modifyDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column language.isDeleted
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private Integer isdeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column language.languageId
     *
     * @return the value of language.languageId
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public String getLanguageid() {
        return languageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column language.languageId
     *
     * @param languageid the value for language.languageId
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setLanguageid(String languageid) {
        this.languageid = languageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column language.languageName
     *
     * @return the value of language.languageName
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public String getLanguagename() {
        return languagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column language.languageName
     *
     * @param languagename the value for language.languageName
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setLanguagename(String languagename) {
        this.languagename = languagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column language.creatDate
     *
     * @return the value of language.creatDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public Date getCreatdate() {
        return creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column language.creatDate
     *
     * @param creatdate the value for language.creatDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setCreatdate(Date creatdate) {
        this.creatdate = creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column language.modifyDate
     *
     * @return the value of language.modifyDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column language.modifyDate
     *
     * @param modifydate the value for language.modifyDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

	public Integer getIsdeleted() {
		return isdeleted;
	}

	public void setIsdeleted(Integer isdeleted) {
		this.isdeleted = isdeleted;
	}
    
    
}