package com.desksoft.entity;

import java.util.Date;

public class MotionArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column motion_article.ma_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String maId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column motion_article.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column motion_article.user_name
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column motion_article.title
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column motion_article.gmt_create
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column motion_article.gmt_modify
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column motion_article.motion_start
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private Date motionStart;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column motion_article.content
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String content;
    
    private Integer up ; 
    
    private Integer down ;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column motion_article.ma_id
     *
     * @return the value of motion_article.ma_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getMaId() {
        return maId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column motion_article.ma_id
     *
     * @param maId the value for motion_article.ma_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setMaId(String maId) {
        this.maId = maId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column motion_article.user_id
     *
     * @return the value of motion_article.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column motion_article.user_id
     *
     * @param userId the value for motion_article.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column motion_article.user_name
     *
     * @return the value of motion_article.user_name
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column motion_article.user_name
     *
     * @param userName the value for motion_article.user_name
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column motion_article.title
     *
     * @return the value of motion_article.title
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column motion_article.title
     *
     * @param title the value for motion_article.title
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column motion_article.gmt_create
     *
     * @return the value of motion_article.gmt_create
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column motion_article.gmt_create
     *
     * @param gmtCreate the value for motion_article.gmt_create
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column motion_article.gmt_modify
     *
     * @return the value of motion_article.gmt_modify
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column motion_article.gmt_modify
     *
     * @param gmtModify the value for motion_article.gmt_modify
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column motion_article.motion_start
     *
     * @return the value of motion_article.motion_start
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public Date getMotionStart() {
        return motionStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column motion_article.motion_start
     *
     * @param motionStart the value for motion_article.motion_start
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setMotionStart(Date motionStart) {
        this.motionStart = motionStart;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column motion_article.content
     *
     * @return the value of motion_article.content
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column motion_article.content
     *
     * @param content the value for motion_article.content
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

	public Integer getUp() {
		return up;
	}

	public void setUp(Integer up) {
		this.up = up;
	}

	public Integer getDown() {
		return down;
	}

	public void setDown(Integer down) {
		this.down = down;
	}
}