package com.desksoft.entity;

import java.util.Date;

public class Tooladdress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tooladdress.taId
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private String taid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tooladdress.taName
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private String taname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tooladdress.address
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tooladdress.sequence
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tooladdress.creatDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private Date creatdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tooladdress.modifyDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tooladdress.isDeleted
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    private Short isdeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tooladdress.taId
     *
     * @return the value of tooladdress.taId
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public String getTaid() {
        return taid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tooladdress.taId
     *
     * @param taid the value for tooladdress.taId
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setTaid(String taid) {
        this.taid = taid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tooladdress.taName
     *
     * @return the value of tooladdress.taName
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public String getTaname() {
        return taname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tooladdress.taName
     *
     * @param taname the value for tooladdress.taName
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setTaname(String taname) {
        this.taname = taname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tooladdress.address
     *
     * @return the value of tooladdress.address
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tooladdress.address
     *
     * @param address the value for tooladdress.address
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tooladdress.sequence
     *
     * @return the value of tooladdress.sequence
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tooladdress.sequence
     *
     * @param sequence the value for tooladdress.sequence
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tooladdress.creatDate
     *
     * @return the value of tooladdress.creatDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public Date getCreatdate() {
        return creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tooladdress.creatDate
     *
     * @param creatdate the value for tooladdress.creatDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setCreatdate(Date creatdate) {
        this.creatdate = creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tooladdress.modifyDate
     *
     * @return the value of tooladdress.modifyDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tooladdress.modifyDate
     *
     * @param modifydate the value for tooladdress.modifyDate
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tooladdress.isDeleted
     *
     * @return the value of tooladdress.isDeleted
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public Short getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tooladdress.isDeleted
     *
     * @param isdeleted the value for tooladdress.isDeleted
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    public void setIsdeleted(Short isdeleted) {
        this.isdeleted = isdeleted;
    }
}