package com.desksoft.entity;

public class UploadPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_pic.pic_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_pic.a_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_pic.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_pic.user_name
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_pic.pic_url
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    private String picUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_pic.pic_id
     *
     * @return the value of upload_pic.pic_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_pic.pic_id
     *
     * @param picId the value for upload_pic.pic_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setPicId(String picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_pic.a_id
     *
     * @return the value of upload_pic.a_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_pic.a_id
     *
     * @param aId the value for upload_pic.a_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setaId(String aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_pic.user_id
     *
     * @return the value of upload_pic.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_pic.user_id
     *
     * @param userId the value for upload_pic.user_id
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_pic.user_name
     *
     * @return the value of upload_pic.user_name
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_pic.user_name
     *
     * @param userName the value for upload_pic.user_name
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_pic.pic_url
     *
     * @return the value of upload_pic.pic_url
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_pic.pic_url
     *
     * @param picUrl the value for upload_pic.pic_url
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }
}