

insert into t_agroup(g_id,name,descr,url,logo,type,acount,gmt_create,gmt_modify) values(1,'ZHIHU','this is zhihu','http://daily.zhihu.com/','http://daily.zhihu.com/img/new_home_v3/top_logo.png',1,0,now(),now()) ;


insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('GOOGLE','Google','https://news.cnblogs.com/n/topic_1.htm','http://images2015.cnblogs.com/news_topic/20150902111809872-2061679551.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('APPLE','Apple','https://news.cnblogs.com/n/topic_82.htm','http://images0.cnblogs.com/news_topic/apple.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('WEIRUAN','微软','https://news.cnblogs.com/n/topic_2.htm','http://images0.cnblogs.com/news_topic/微软.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('KEXUETANSUO','科学探索','https://news.cnblogs.com/n/topic_319.htm','http://images0.cnblogs.com/news_topic/science.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('CHENGXUYUAN','程序员','https://news.cnblogs.com/n/topic_335.htm','http://images0.cnblogs.com/news_topic/programmer.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('FACEBOOK','Facebook','https://news.cnblogs.com/n/topic_21.htm','http://images0.cnblogs.com/news_topic/facebook.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('IPHONE','iPhone','https://news.cnblogs.com/n/topic_61.htm','http://images0.cnblogs.com/news_topic/iphone.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('ANDROID','Android','https://news.cnblogs.com/n/topic_148.htm','http://images2015.cnblogs.com/news_topic/20161020185521154-1185360701.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('CHUANGYE','创业','https://news.cnblogs.com/n/topic_367.htm','http://images2015.cnblogs.com/news_topic/20150908155311528-141424242.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('BAIDU','百度','https://news.cnblogs.com/n/topic_5.htm','http://images0.cnblogs.com/news_topic/baidu.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('NUOJIYA','诺基亚','https://news.cnblogs.com/n/topic_141.htm','http://images0.cnblogs.com/news_topic/nokia.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('SANXING','三星','https://news.cnblogs.com/n/topic_251.htm','http://images0.cnblogs.com/news_topic/samsung.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('ALIBABA','阿里巴巴','https://news.cnblogs.com/n/topic_6.htm','http://images0.cnblogs.com/news_topic/20150529141337860.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('YAMAXUN','亚马逊','https://news.cnblogs.com/n/topic_167.htm','http://images0.cnblogs.com/news_topic/amazon.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('IPAD','iPad','https://news.cnblogs.com/n/topic_280.htm','http://images0.cnblogs.com/news_topic/iPad.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('TWITTER','Twitter','https://news.cnblogs.com/n/topic_111.htm','http://images0.cnblogs.com/news_topic/twitter.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('WINDOWSPHONE','Windows Phone','https://news.cnblogs.com/n/topic_290.htm','http://images0.cnblogs.com/news_topic/windows_phone.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('WINDOWS8','Windows 8','https://news.cnblogs.com/n/topic_242.htm','http://images0.cnblogs.com/news_topic/windows 8.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('TENGXUN','腾讯','https://news.cnblogs.com/n/topic_7.htm','http://images0.cnblogs.com/news_topic/tencent.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('HULIANWANG','互联网','https://news.cnblogs.com/n/topic_257.htm','http://images0.cnblogs.com/news_topic/internet.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('XIAOMI','小米','https://news.cnblogs.com/n/topic_368.htm','http://images0.cnblogs.com/news_topic/小米.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('TAOBAO','淘宝','https://news.cnblogs.com/n/topic_87.htm','http://images0.cnblogs.com/news_topic/taobao.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('FIREFOX','Firefox','https://news.cnblogs.com/n/topic_41.htm','http://images0.cnblogs.com/news_topic/firefox.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('JINGDONG','京东','https://news.cnblogs.com/n/topic_228.htm','http://images0.cnblogs.com/news_topic/logo-2013.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('NASA','NASA','https://news.cnblogs.com/n/topic_345.htm','http://images0.cnblogs.com/news_topic/nasa.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('QIAOBUSI','乔布斯','https://news.cnblogs.com/n/topic_180.htm','http://images0.cnblogs.com/news_topic/jobs_80.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('CHROME','Chrome','https://news.cnblogs.com/n/topic_145.htm','http://images0.cnblogs.com/news_topic/chrome.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('MAYUN','马云','https://news.cnblogs.com/n/topic_193.htm','http://images0.cnblogs.com/news_topic/mxyqd2gs.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('LINUX','Linux','https://news.cnblogs.com/n/topic_96.htm','http://images0.cnblogs.com/news_topic/linux.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('WINDOWS7','Windows 7','https://news.cnblogs.com/n/topic_147.htm','http://images0.cnblogs.com/news_topic/windows_7.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('INTEL','Intel','https://news.cnblogs.com/n/topic_12.htm','http://images0.cnblogs.com/news_topic/intel.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('QIHU360','奇虎360','https://news.cnblogs.com/n/topic_133.htm','http://images0.cnblogs.com/news_topic/ec6c7e9e.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('WEIXIN','微信','https://news.cnblogs.com/n/topic_372.htm','http://images0.cnblogs.com/news_topic/微信.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('SUONI','索尼','https://news.cnblogs.com/n/topic_171.htm','http://images0.cnblogs.com/news_topic/song.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('IE','IE','https://news.cnblogs.com/n/topic_91.htm','http://images0.cnblogs.com/news_topic/IE7.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('HUAWEI','华为','https://news.cnblogs.com/n/topic_188.htm','http://images0.cnblogs.com/news_topic/200782215744993.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('ZHIFUBAO','支付宝','https://news.cnblogs.com/n/topic_131.htm','http://images0.cnblogs.com/news_topic/20150709134830408.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('BAOXUE','暴雪','https://news.cnblogs.com/n/topic_124.htm','http://images0.cnblogs.com/news_topic/blizz-logo.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('HUIPU','惠普','https://news.cnblogs.com/n/topic_151.htm','http://images0.cnblogs.com/news_topic/hp.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('SHENGDA','盛大','https://news.cnblogs.com/n/topic_121.htm','http://images0.cnblogs.com/news_topic/snda.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('HTC','HTC','https://news.cnblogs.com/n/topic_289.htm','http://images0.cnblogs.com/news_topic/htc_logo.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('IBM','IBM','https://news.cnblogs.com/n/topic_88.htm','http://images0.cnblogs.com/news_topic/ibm.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('IPHONE6PLUS','iPhone 6 plus','https://news.cnblogs.com/n/topic_515.htm','http://images0.cnblogs.com/news_topic/20150202125808578.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('LIANXIANG','联想','https://news.cnblogs.com/n/topic_158.htm','http://images0.cnblogs.com/news_topic/20150602081438742.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('ORACLE','Oracle','https://news.cnblogs.com/n/topic_97.htm','http://images0.cnblogs.com/news_topic/oracle.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('UBUNTU','ubuntu','https://news.cnblogs.com/n/topic_42.htm','http://images0.cnblogs.com/news_topic/ubuntu.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('SHEJI','设计','https://news.cnblogs.com/n/topic_104.htm','http://images0.cnblogs.com/news_topic/design.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('ADOBE','Adobe','https://news.cnblogs.com/n/topic_4.htm','http://images0.cnblogs.com/news_topic/adobe.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('QQ','QQ','https://news.cnblogs.com/n/topic_200.htm','http://images0.cnblogs.com/news_topic/qq.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('GROUPON','Groupon','https://news.cnblogs.com/n/topic_315.htm','http://images0.cnblogs.com/news_topic/logo_groupon.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('ZHOUHONGYI','周鸿祎','https://news.cnblogs.com/n/topic_250.htm','http://images2015.cnblogs.com/news_topic/20160418130807398-2054839280.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('XBOX','Xbox','https://news.cnblogs.com/n/topic_299.htm','http://images0.cnblogs.com/news_topic/xbox.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('MOTUOLUOLA','摩托罗拉','https://news.cnblogs.com/n/topic_272.htm','http://images0.cnblogs.com/news_topic/motorola-logo.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('YUNJISUAN','云计算','https://news.cnblogs.com/n/topic_110.htm','http://images0.cnblogs.com/news_topic/Cloud_Computing.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('LESHIWANG','乐视网','https://news.cnblogs.com/n/topic_316.htm','http://images0.cnblogs.com/news_topic/letv.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('XINLANGWEIBO','新浪微博','https://news.cnblogs.com/n/topic_347.htm','http://images0.cnblogs.com/news_topic/t_sina_logo.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('BING','Bing','https://news.cnblogs.com/n/topic_179.htm','http://images0.cnblogs.com/news_topic/bing.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('BIER·GAICI','比尔·盖茨','https://news.cnblogs.com/n/topic_84.htm','http://images0.cnblogs.com/news_topic/bill_gates.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('YIDONGHULIANWANG','移动互联网','https://news.cnblogs.com/n/topic_340.htm','http://images0.cnblogs.com/news_topic/mobile_internet.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('YOUTUBE','YouTube','https://news.cnblogs.com/n/topic_22.htm','http://images0.cnblogs.com/news_topic/youtube.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('SNS','sns','https://news.cnblogs.com/n/topic_127.htm','http://images0.cnblogs.com/news_topic/sns.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('SURFACE','surface','https://news.cnblogs.com/n/topic_379.htm','http://images0.cnblogs.com/news_topic/surface.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('HTML5','HTML5','https://news.cnblogs.com/n/topic_296.htm','http://images0.cnblogs.com/news_topic/html5.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('JAVA','Java','https://news.cnblogs.com/n/topic_94.htm','http://images0.cnblogs.com/news_topic/java.gif',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('TESLA','Tesla','https://news.cnblogs.com/n/topic_429.htm','http://images0.cnblogs.com/news_topic/tesla.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('HEIMEI','黑莓','https://news.cnblogs.com/n/topic_705.htm','http://images2015.cnblogs.com/news_topic/20160330090929613-1116517125.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('JIQIREN','机器人','https://news.cnblogs.com/n/topic_624.htm','http://images2015.cnblogs.com/news_topic/20150911111442153-33706165.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('ITBOKE','IT博客','https://news.cnblogs.com/n/topic_132.htm','http://images0.cnblogs.com/news_topic/ITblog.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('APPLEWATCH','Applewatch','https://news.cnblogs.com/n/topic_514.htm','http://images2015.cnblogs.com/news_topic/20151119093743436-66938402.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('ZHONGGUOLIANTONG','中国联通','https://news.cnblogs.com/n/topic_177.htm','http://images0.cnblogs.com/news_topic/未命名-1.jpg',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('.NET','.Net','https://news.cnblogs.com/n/topic_164.htm','http://images0.cnblogs.com/news_topic/msdotnet.png',1,0,now(),now()) ;
insert into t_agroup(name,descr,url,logo,type,acount,gmt_create,gmt_modify) values('DANGDANG','当当','https://news.cnblogs.com/n/topic_175.htm','http://images0.cnblogs.com/news_topic/20150529154929266.png',1,0,now(),now()) ;



