package com.desksoft.entity.mapper;

import com.desksoft.entity.APoint;


public interface APointMapper {


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table a_point
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	int deleteByPrimaryKey(String aId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table a_point
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	int insert(APoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table a_point
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	int insertSelective(APoint record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table a_point
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	APoint selectByPrimaryKey(String aId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table a_point
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	int updateByPrimaryKeySelective(APoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table a_point
	 * @mbggenerated  Sun Jul 14 01:45:43 CST 2013
	 */
	int updateByPrimaryKey(APoint record);
}