package com.desksoft.entity.mapper;

import com.desksoft.entity.AReplay;

public interface AReplayMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_replay
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int deleteByPrimaryKey(String rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_replay
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int insert(AReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_replay
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int insertSelective(AReplay record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_replay
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    AReplay selectByPrimaryKey(String rId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_replay
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int updateByPrimaryKeySelective(AReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_replay
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(AReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_replay
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int updateByPrimaryKey(AReplay record);
}