package com.desksoft.entity.mapper;

import com.desksoft.entity.BindRelation;

public interface BindRelationMapper {
    /**

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bind_relation
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int insert(BindRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bind_relation
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int insertSelective(BindRelation record);

}