package com.desksoft.entity.mapper;

import java.util.List;
import java.util.Map;

import com.desksoft.dao.SqlMapper;
import com.desksoft.entity.Category;

public interface CategoryMapper  extends SqlMapper{


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int deleteByPrimaryKey(String categoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int insertSelective(Category record);


    Category selectByPrimaryKey(String categoryid);

    
    List<Category> queryCategory(Map<String,Object> params);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int updateByPrimaryKey(Category record);

}