package com.desksoft.entity.mapper;

import java.util.List;
import java.util.Map;

import com.desksoft.dao.SqlMapper;
import com.desksoft.entity.Categorydetail;

public interface CategorydetailMapper extends SqlMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorydetail
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int deleteByPrimaryKey(String categorydetailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorydetail
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int insert(Categorydetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorydetail
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int insertSelective(Categorydetail record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorydetail
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    Categorydetail selectByPrimaryKey(String categorydetailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorydetail
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int updateByPrimaryKeySelective(Categorydetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorydetail
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int updateByPrimaryKey(Categorydetail record);

	List<Categorydetail> selectByParentId(String categoryId);

	Integer updateSequ(Map<String, Object> map);
	
	
	List<Categorydetail> queryCategoryDetail(Map<String, Object> map) ;
}