package com.desksoft.entity.mapper;

import java.util.List;

import com.desksoft.dao.SqlMapper;
import com.desksoft.entity.Language;

public interface LanguageMapper extends SqlMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int deleteByPrimaryKey(String languageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */  
    int insert(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int insertSelective(Language record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    Language selectByPrimaryKey(String languageid);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    List<Language> selectAll();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int updateByPrimaryKeySelective(Language record);

    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int updateByPrimaryKey(Language record);
}