package com.desksoft.entity.mapper;

import com.desksoft.entity.MotionArticle;

public interface MotionArticleMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motion_article
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int deleteByPrimaryKey(String maId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motion_article
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int insert(MotionArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motion_article
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int insertSelective(MotionArticle record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motion_article
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    MotionArticle selectByPrimaryKey(String maId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motion_article
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int updateByPrimaryKeySelective(MotionArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motion_article
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(MotionArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motion_article
     *
     * @mbggenerated Sun Jul 14 01:45:43 CST 2013
     */
    int updateByPrimaryKey(MotionArticle record);
}