package com.desksoft.entity.mapper;

import com.desksoft.entity.Tooladdress;

public interface TooladdressMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tooladdress
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int deleteByPrimaryKey(String taid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tooladdress
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int insert(Tooladdress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tooladdress
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int insertSelective(Tooladdress record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tooladdress
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    Tooladdress selectByPrimaryKey(String taid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tooladdress
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int updateByPrimaryKeySelective(Tooladdress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tooladdress
     *
     * @mbggenerated Mon Dec 31 22:18:48 CST 2012
     */
    int updateByPrimaryKey(Tooladdress record);
}